name: Main

on:
  push:
    branches: [ main, beta ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]

jobs:
  main:
    name: pipeline
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm ci --ignore-scripts
          npm install --no-save @microsoft/eslint-formatter-sarif@2.1.7

      - name: Lint
        run: npm run lint

      - name: Semantic Release
        if: ${{ github.event_name != 'pull_request' }}
        uses: cycjimmy/semantic-release-action@v3.0.0
        with:
          dry_run: true
        env:
          GL_TOKEN: ${{ secrets.GL_TOKEN }}
          # NPM_TOKEN: ${{ secrets.NPM_TOKEN }} # TODO
