name: Main

on:
  push:
    branches: [ main, beta ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm ci --ignore-scripts
          npm install --no-save @microsoft/eslint-formatter-sarif@2.1.7

      - name: Run ESLint
        run: npm run lint
